### ISSUE TITLE
I always meet the following error when training. Anyone know what's going on here? ?

### ISSUE THREAD

**Issue by zgf6781882** [imatge-upc/rvos#34]
Traceback (most recent call last):
  File "train_previous_mask.py", line 384, in <module>
    trainIters(args)
  File "train_previous_mask.py", line 252, in trainIters
    loaders = init_dataloaders(args)
  File "train_previous_mask.py", line 50, in init_dataloaders
    use_prev_mask = False) #use_prev_mask is True only for evaluation
  File "C:\rvos\src\dataloader\dataset_utils.py", line 25, in get_dataset
    use_prev_mask = use_prev_mask)
  File "C:\vos\src\dataloader\davis2017.py", line 124, in __init__
    self.sequences = [Sequence(self._phase, s.name, lmdb_env=lmdb_env_seq) for s in self._db_sequences]
  File "C:\rvos\src\dataloader\davis2017.py", line 124, in <listcomp>
    self.sequences = [Sequence(self._phase, s.name, lmdb_env=lmdb_env_seq) for s in self._db_sequences]
  File "C:\rvos\src\dataloader\base.py", line 98, in __init__
    split,osp.join(cfg.PATH.SEQUENCES,name), regex, lmdb_env=lmdb_env)
  File "C:\rvos\src\dataloader\base.py", line 71, in __init__
    super(BaseLoader, self).__init__(_files, load_func=load_func)
  File "C:\Users\user\.conda\envs\rvos\lib\site-packages\skimage\io\collection.py", line 188, in __init__
    raise TypeError('Invalid pattern as input.')
TypeError: Invalid pattern as input.

**Comment by Meryl-Fang** [comment]
Met the same error if I used LMDB generators. Were you able to solve this problem?

**Comment by bereket-meley** [comment]
Hi 
Getting the same issue here, any solution

**Comment by yaelalonNT** [comment]
Hi, the same. Do you have a solution?

**Comment by yaelalonNT** [comment]
I solved the issue by downgrading the version of scikit-image
